### ISSUE TITLE
some issues about predict

### ISSUE THREAD

**Issue by shaoshuai-luo** [yhlleo/RoadNet#1]
Dear author,
    I would like to ask how to predict new pictures after the model is trained?
    looking forward to your reply!
    Thank you very much

    shaoshuailuo
    16-1-2022

**Comment by yhlleo** [comment]
Hi @shaoshuai-luo, did you try with this repo: [yhlleo/DeepSegmentor](https://github.com/yhlleo/DeepSegmentor)? I think you can find the answer there.
