### ISSUE TITLE
Ottawa-7 has labels inside it 

### ISSUE THREAD

**Issue by londumas** [yhlleo/RoadNet#2]
Ottawa-7 has labels inside it.

![image](https://user-images.githubusercontent.com/3166436/225686889-53d248af-85fc-405e-9727-14fbc434da6f.png)

**Comment by yhlleo** [comment]
Yes, it is a mistake. Thanks!

**Comment by londumas** [comment]
@yhlleo Thank you for the answer, howerver it does not seem to be fixed in the google-drive repo.
Could you do this?

**Comment by yhlleo** [comment]
@londumas, I tried to find the original data. Unfortunately, I lost the original data.
